### ISSUE TITLE
Improvement Thoughts

### ISSUE THREAD

**Issue by chrisjsewell** [executablebooks/mdformat#11]
As discussed in https://github.com/executablebooks/markdown-it-py/issues/10, great work!

A few thoughts off the cuff:

- use click for CLI, which can also read configuration from a config file (see https://github.com/executablebooks/scss-compile for an example)
- Plugin system for code block formatting (e.g. black for python blocks)
- Add tox configuration, for test automation

**Comment by hukkinj1** [comment]
Thanks for your thoughts!

> * use click for CLI, which can also read configuration from a config file (see https://github.com/executablebooks/scss-compile for an example)

I think this is a great idea and should be implemented if we end up having configuration. Currently there is zero configuration, so I'd be hesitant to add a new dependency if `argparse` can still get the job done just fine.

> * Plugin system for code block formatting (e.g. black for python blocks)

I really like this. I made a separate issue https://github.com/hukkinj1/mdformat/issues/12

> * Add tox configuration, for test automation

If there is a problem that this would solve, I don't see why not. Currently though we have no `sys.version_info` checks (meaning all Python versions do pretty much the same stuff), and no dependencies where we would need to test support for more than one major version, so while developing I've found simply running `pytest` sufficient. CI runs tests on all OS and py versions though.

**Comment by chrisjsewell** [comment]
> If there is a problem that this would solve, I don't see why not

Mainly just for me lol; when jumping around between lots of repositories, its just really helpful to be able to quickly run tox, rather than manually setting-up/initializing new dev environments every time

**Comment by chrisjsewell** [comment]
Whaay thanks @hukkinj1, welcome to EBP 🥳  (cc @choldgraf @mmcky @AakashGfude).
Think I'll just delete the whole package now 😆

**Comment by hukkinj1** [comment]
> Think I'll just delete the whole package now

![liam](https://user-images.githubusercontent.com/3275109/93253890-31c45580-f7a0-11ea-9a49-6d4b18d0c6d1.gif)

**Comment by chrisjsewell** [comment]
even if you found me, you would still have to wait a few weeks in quarantine 😆

**Comment by hukkinj1** [comment]
Oh man, add another two weeks to that after the flight back. It might just not be worth it. You win.

To conclude this ticket: I think there's no immediate action items on this issue, so closing. A tox PR is welcome if someone finds it helpful. Click shouldn't IMO be rushed until it solves a problem (e.g. reading a configuration file).
