### ISSUE TITLE
Requires a `language_version` override in Python 2 environments

### ISSUE THREAD

**Issue by ehontoria** [executablebooks/mdformat#169]
**Describe the bug**

When attempting to install the hook I would assume all you have to do is have a `.pre-commit-config.yaml` with the following configuration:
```
-   repo: https://github.com/executablebooks/mdformat
    rev: 0.5.6
    hooks:
        -   id: mdformat
```

However, for any Python 2 environment (I am on `2.7.16`) it seems you have to put in a `language_version` override to get it to install properly resulting in (something like):
```
-   repo: https://github.com/executablebooks/mdformat
    rev: 0.5.6
    hooks:
        -   id: mdformat
            language_version: 3.7.7
```
I believe there should be a default language version set so that you don't have to override this value.

The reason I ask about this is because other hooks `black` for example also only run on Python 3, and it does not need this override.

**To Reproduce**

1. Create a python virtual environment where the version of python is not supported for this hook
2. Attempt to create a pre-commit config without `language_version` set.
3. `pre-commit install --install-hooks`

**Expected behavior**

Expected behavior is that it installs properly.

**Environment**

- Python Version [e.g. 3.7.1]: 2.7.16
- Package versions or output of `jupyter-book --version`: 0.5.6
- Operating System: MacOS

**Additional context**

N/A

**Comment by hukkinj1** [comment]
Thanks for the issue!

Firstly, I'm sorry that you have to work with Python 2 :smile: 

Black sets `language_version: python3` in their `.pre-commit-hooks.yaml`. I think we should set the same configuration in this project.

For now I assume the following configuration will work for you:

```yaml
- repo: https://github.com/executablebooks/mdformat
  rev: 0.6.4
  hooks:
  - id: mdformat
    language_version: python3
```

**Comment by ehontoria** [comment]
Seems reasonable. 

And don't worry we're moving to Python 3 very soon (although, I wish it had been sooner) 😸 .
