### ISSUE TITLE
Support enforcing line breaks after "end of sentence"

### ISSUE THREAD

**Issue by choldgraf** [executablebooks/mdformat#222]
It would be useful if we could use a feature flag to enforce "one sentence per line". This basically means following the first 4 rules of the ["semantic line breaks" spec](https://sembr.org/) (and most importantly, following all of the `MUST` rules).

I've found this to give much of the "benefits of sembr" without much extra work.

**Comment by hukkin** [comment]
Thanks for the issue!

Please have a look at https://github.com/executablebooks/mdformat/issues/4. This seems like a duplicate?

Extracting sentences from text is not an easy task (especially given other languages besides English) so my most recent thoughts are that this should perhaps be researched in a plugin to see if it works. One can not simply break lines after a punctuation char (e.g. "Temple of Doom was discovered by Dr. Jones." will be wrapped incorrectly).

Also, inline code and emphasis blocks located mid sentence add some challenge.

**Comment by choldgraf** [comment]
Ah indeed I think it's a duplicate based on content. I didn't think to look into that issue after looking at the title because it didn't mention sentence-based line breaks.

Also agree w/ all of your points!

**Comment by hukkin** [comment]
Cool, and I agree that the issue title was pretty bad :smile: Fixed that, thanks.
