### ISSUE TITLE
Line wrap changes short lines (and throws error on --check)

### ISSUE THREAD

**Issue by cornim** [executablebooks/mdformat#242]
**Describe the bug**

When mdformat is used with the `--wrap` and `--check` option and multiple lines are shorter than what is specified in wrap. The file is flagged as not formatted.

**To Reproduce**

```bash
docker run -it --rm ubuntu
apt update && apt install -y python3 python3-pip
pip3 install mdformat
cat > test.md << EOF
Test aa
and test bb
EOF
mdformat --check --wrap 80 test.md
```

**Expected behavior**

No error as no line is too long.

**Additional context**

One could argue that, without the `--check` option. Shorter lines should be left alone as well and I think that is pretty much how any other formatter does it but I can also see arguments why it should be changed. In all likelihood keeping the check an no-check behavior consistent is probably a good idea.

**Comment by hukkin** [comment]
The seems like intended behavior to me. All that `--check` flag does is it checks whether running `mdformat` without it would introduce changes or not. In this case the paragraph is not formatted in a way that satisfies `mdformat` so an error on `--check` is expected.

**Comment by cornim** [comment]
Unfortunately this kind of behavior makes it almost impossible to use mdformat in check mode in a CI pipeline as it will almost always complain about something not be formatted correctly (and at the same time lacking any output about what exactly is wrong).
Also I do think it is notable that mdformat works differently in this regard from pretty much any other formatter or linter. Is there a specific reason for this design choice?

**Comment by hukkin** [comment]
> Unfortunately this kind of behavior makes it almost impossible to use mdformat in check mode in a CI pipeline

I do recommend using a pre-commit hook or otherwise running the formatter before pushing.

> Also I do think it is notable that mdformat works differently in this regard from pretty much any other formatter

Please correct me if I'm wrong, but as far as I know, this is how pretty much all formatters I've used work (Black, Prettier, rustfmt, gofmt...).

---

Sounds to me like you might be more satisfied using a linter than an opinionated formatter. There should be `markdownlint` or similar for Markdown.

**Comment by cornim** [comment]
Using a linter sounds like a good idea. Thanks for the advice.
