### ISSUE TITLE
Pass info string to code formatter functions

### ISSUE THREAD

**Issue by chrisjsewell** [executablebooks/mdformat#26]
https://github.com/executablebooks/mdformat/blob/4b3c84e43b27b32a50fd0d4ff064179603b479bb/mdformat/_renderer/token_renderers.py#L94

For a use-case: in the [MyST-Markdown](https://jupytext.readthedocs.io/en/latest/formats.html#myst-markdown) format, code cells are defined like:

````
```{code-cell} ipython3
:tags: [hide-output, show-input]

print("Hallo!")
```
````

and so, to create a formatter plugin for this, I would set the language as "{code-cell}", but then would also need to have access to the rest of the string to determine how to format

**Comment by chrisjsewell** [comment]
Obviously you will need to adapt your current plugins to handle this, which is why I wanted to raise this now, before you made more!

**Comment by hukkinj1** [comment]
Make sense. How does https://github.com/executablebooks/mdformat/pull/27 seem to you?

**Comment by chrisjsewell** [comment]
👌
