### ISSUE TITLE
flake8 flags "W503 line break before binary operator" rule violations

### ISSUE THREAD

**Issue by jamesquilty** [executablebooks/mdformat#270]
### Describe the problem

My clone sees flake8 pre-commit hook fail on these files:

- mdformat/src/mdformat/renderer/_util.py
- mdformat/src/mdformat/_conf.py
- mdformat/src/mdformat/_cli.py
- mdformat/tests/test_cli.py

black doesn't seem to care about this, and neither does pylint (which flags other violations - see context, below).

I'm not quite sure what's going on, is this reproducible on someone else's system?

### Steps to reproduce

```shell
$ git clone git@github.com:executablebooks/mdformat.git
Cloning into 'mdformat'...
remote: Enumerating objects: 2159, done.
remote: Counting objects: 100% (846/846), done.
remote: Compressing objects: 100% (374/374), done.
remote: Total 2159 (delta 563), reused 641 (delta 439), pack-reused 1313
Receiving objects: 100% (2159/2159), 586.12 KiB | 369.00 KiB/s, done.
Resolving deltas: 100% (1476/1476), done.

$ pre-commit run --all-files
Check Yaml...............................................................Passed
Check Toml...............................................................Passed
type annotations not comments............................................Passed
check blanket noqa.......................................................Passed
check blanket type ignore................................................Passed
Strip unnecessary `# noqa`s..............................................Passed
isort....................................................................Passed
black....................................................................Passed
docformatter.............................................................Passed
flake8...................................................................Failed
- hook id: flake8
- exit code: 1

src/mdformat/_cli.py:87:17: W503 line break before binary operator
src/mdformat/_cli.py:88:17: W503 line break before binary operator
src/mdformat/_cli.py:90:21: W503 line break before binary operator
src/mdformat/renderer/_util.py:20:5: W503 line break before binary operator
src/mdformat/renderer/_util.py:21:5: W503 line break before binary operator
src/mdformat/renderer/_util.py:22:5: W503 line break before binary operator
src/mdformat/renderer/_util.py:23:5: W503 line break before binary operator
src/mdformat/renderer/_util.py:24:5: W503 line break before binary operator
src/mdformat/renderer/_util.py:25:5: W503 line break before binary operator
src/mdformat/renderer/_util.py:70:9: W503 line break before binary operator
src/mdformat/renderer/_util.py:71:9: W503 line break before binary operator
src/mdformat/renderer/_util.py:130:13: W503 line break before binary operator
src/mdformat/renderer/_util.py:153:9: W503 line break before binary operator
src/mdformat/renderer/_util.py:154:9: W503 line break before binary operator
src/mdformat/renderer/_util.py:167:13: W503 line break before binary operator
src/mdformat/_conf.py:52:13: W503 line break before binary operator
tests/test_plugins.py:206:9: W503 line break before binary operator
tests/test_cli.py:164:9: W503 line break before binary operator
tests/test_cli.py:189:9: W503 line break before binary operator
```

### The version of Python you're using

Python 3.7.3

### Your operating system

macOS

### Additional context

pylint seems happier with black's formatting, only raising C0114 and C0116 docstring rule violations:

```shell
$ pylint src/mdformat/renderer/_util.py
************* Module mdformat.renderer._util
src/mdformat/renderer/_util.py:1:0: C0114: Missing module docstring (missing-module-docstring)
src/mdformat/renderer/_util.py:29:0: C0116: Missing function or method docstring (missing-function-docstring)
src/mdformat/renderer/_util.py:44:0: C0116: Missing function or method docstring (missing-function-docstring)
src/mdformat/renderer/_util.py:56:8: C0103: Variable name "c" doesn't conform to snake_case naming style (invalid-name)
src/mdformat/renderer/_util.py:66:0: C0116: Missing function or method docstring (missing-function-docstring)
src/mdformat/renderer/_util.py:84:0: C0116: Missing function or method docstring (missing-function-docstring)

-----------------------------------
Your code has been rated at 9.44/10
```

**Comment by hukkin** [comment]
The `W503` check is disabled by default in flake8, so it seems that you're reading a flake8 configuration from somewhere outside this repository that enables that check.

Regarding the steps to reproduce: you're missing 
```sh
cd mdformat/
```
after the `git clone`. Maybe you're running pre-commit in the wrong directory?

Regarding pyling: we don't use that tool in mdformat.

**Comment by jamesquilty** [comment]
I think there's some problem with Python on my system which is interfering with the default configuration 😦. Yes, I missed one step; not worth fixing now; pre-commit was run from the repository root directory. This problem appears to be restricted to my systems, so closing.

**Comment by jamesquilty** [comment]
FWIW, this was caused by some particularly capricious behaviour on the part of `flake8` which was _hard_ to track down: `exclude` and `ignore` lines in `~/.config/flake8` have the pernicious side-effect of silently _including_ and _enabling_ rules. and the `flake8` documentation doesn't warn about this. Avoiding silliness like this was one of the reasons I switched, more than 2 years ago, from `flake8` to `pylint` <https://pylint.org/>. We should consider switching in mdformat.

**Comment by hukkin** [comment]
I much prefer flake8 to pylint. You should use `extend-exclude` and `extend-ignore` to avoid overriding the defaults.

**Comment by jamesquilty** [comment]
I much prefer tools that are not prone to unaccountable changes in behaviour. Yes, I know about `extend-exclude` and `extend-ignore` _now_, but it cost me more than a few hours of frustration trying to find where the rule had been explicitly enabled (even you expected this) &mdash; it hadn't.
