### ISSUE TITLE
Extra whitespace when converting indented code block to fenced code block

### ISSUE THREAD

**Issue by rpdelaney** [executablebooks/mdformat#272]
### Describe the problem

Before:

```markdown
# Overview

[direnv](https://direnv.net/) is an MIT-licensed command-line tool that addresses the hassle of setting per-project environment variables.

## Installation

Via homebrew:

     brew install direnv
```

After:

`````markdown
# Overview

[direnv](https://direnv.net/) is an MIT-licensed command-line tool that addresses the hassle of setting per-project environment variables.

## Installation

Via homebrew:

```
 brew install direnv
```
`````

There is a leading space before `brew install direnv`. If I remove it manually, mdformat does not restore it. Is this intended?

### Link to your repository or website

https://github.com/trussworks/Engineering-Playbook/pull/195#pullrequestreview-762213521

### Steps to reproduce

1. Add "before" markdown to a file
2. Run `mdformat` on it

### The version of Python you're using

3.6.9

### Your operating system

macOS-11.5.2

### Versions of your packages

mdformat 0.7.9 (mdformat_toc: 0.3.0)

**Comment by hukkin** [comment]
Hey, thanks for the report!

This doesn't seem like a bug to me. There are 5 leading spaces in the indented code block. Only 4 are needed so the code block content starts with a space.

Mdformat would be changing Markdown AST and rendered content by stripping the space, so we won't do it.

**Comment by hukkin** [comment]
This is actually one reason why the fenced syntax is better IMO. It makes the error in Markdown source obvious.

**Comment by rpdelaney** [comment]
Makes sense, thanks for the fast response!
