### ISSUE TITLE
Minor error/omission on contributing page

### ISSUE THREAD

**Issue by jamesquilty** [executablebooks/mdformat#275]
### Describe the problem

I was following the instructions on the [Contributing](https://github.com/executablebooks/mdformat/blob/master/docs/contributors/contributing.md) page and step 4 didn't work for me, I think that instead of `pytest` potential contributeor should be instructed to run `poetry pytest`?

That's a really minor problem, of course.

What was puzzling me a bit more, and I don't quite know where to raise it, is that while I'm testing changes locally I'd like to have my changes available. From some reading, I understand that there used to be a way to do this when projects used setuptools, by executing `pip install --editable <path-to-repo>`, but mdformat uses `poetry` and `flit` and I've been completely unable to make it work with setuptools (details below).

How should contributors install their development version of the code so that the `mdformat` command runs the development version?

Is installing the development version something that the current developers do, or is there a better/preferred way to have the development version available from the command line?

### Steps to reproduce

I've tried `pip install setuptools` and creating a `setup.py` file in my local copy (i.e. uncommitted) containing

```python
#!/usr/bin/env python
#
# This file is needed for editable installs (`pip install -e .`).
# Can be removed once the following is resolved
# https://github.com/pypa/packaging-problems/issues/256
from setuptools import setup

# if __name__ == "__main__":
setup()
```

I then tried running `pip install --editable <path-to-repo>` (outside of the `poetry` virtual environment) but this throws an error saying it can't find the setuptools module:

```shell
$ pip install --editable ~/.../mdformat
Obtaining file:///.../mdformat
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
...
  Running setup.py develop for mdformat
    ERROR: Command errored out with exit status 1:
     command: /Library/Frameworks/Python.framework/Versions/3.7/bin/python3.7 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/.../mdformat/setup.py'"'"'; __file__='"'"'/.../mdformat/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps
         cwd: /.../mdformat/
    Complete output (3 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
    ModuleNotFoundError: No module named 'setuptools'
    ----------------------------------------
ERROR: Command errored out with exit status 1: /Library/Frameworks/Python.framework/Versions/3.7/bin/python3.7 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/.../mdformat/setup.py'"'"'; __file__='"'"'/.../mdformat/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.
```

### The version of Python you're using

Python 3.7.3

### Your operating system

macOS

### Versions of your packages

```
setuptools-58.2.0
```

**Comment by jamesquilty** [comment]
Thanks for the reply and the update. `poetry install` appeared to be only creating a virtualenv local to the clone, rather than linking it to the site/user install locations. I couldn't get `pip install --editable <path-to-local-copy>` to work, but running `pip intstall <path-to-local-copy>" after each change was at least propagating the changes centrally - i.e. has the latest changed version of `mdformat` was on the `PATH` and accessible from any directory. Is that how `poetry install` is supposed to work?

Also, is there somewhere better than a closed issue to discuss development environments? 🙂

**Comment by hukkin** [comment]
Yeah Poetry is a developer tool so by default it only operates in a project specific virtual environment. If you _really_ want it to install globally you can run 
```bash
poetry config virtualenvs.create false
```
but I'm not sure why you'd ever want that when developing.

Note that thanks to PEP660 you can also do
```
pip install --editable .
```
as soon as our build backend (`poetry-core`) supports the PEP. The support will be in an upcoming `poetry-core` v1.1.0 release (or you already install from git).

> Also, is there somewhere better than a closed issue to discuss development environments? 

It's not mdformat specific, but Python discord comes to mind https://discord.com/invite/python

**Comment by jamesquilty** [comment]
> but I'm not sure why you'd ever want that when developing.

 [Dogfooding](https://en.wikipedia.org/wiki/Eating_your_own_dog_food).
