### ISSUE TITLE
Wrap bare URIs

### ISSUE THREAD

**Issue by jamesquilty** [executablebooks/mdformat#284]
### Description / Summary

mdformatted output can violate Markdownlint rule [MD034 - Bare URL used](https://github.com/markdownlint/markdownlint/blob/master/docs/RULES.md#md034---bare-url-used). I know that the CommonMark Spec section [6.5 Autolinks](https://spec.commonmark.org/0.30/#autolinks) allows bare URIs and specifies that they not be treated as autolinks, but that's not relevant &mdash; I agree with [MD034](https://github.com/markdownlint/markdownlint/blob/master/docs/RULES.md#md034---bare-url-used) and I want & need my formatter to wrap bare URIs with angled brackets &mdash; otherwise, I will have to do it by hand.

### Value / benefit

The value of this is automating a time-consuming and error-prone manual process, i.e. fulfilling the purpose of a formatter.

### Implementation details

~~I guess that [maybe_add_link_brackets()](https://github.com/executablebooks/mdformat/blob/master/src/mdformat/renderer/_util.py#L75) or its calling function [link()](https://github.com/executablebooks/mdformat/blob/54f549e57a226701c1812fb8a2b478a847172699/src/mdformat/renderer/_context.py#L236) will have to be modified to take~~ bad guess. Still, a configurable option will be required like `wrap_bare_URIs` which defaults to False (current behaviour) but always wraps bare URIs with `<` and `>` when True.

### Tasks to complete

- [ ] find out where bare URIs are to be found and work out how to detect them for wrapping.

**Comment by hukkin** [comment]
Thanks for the issue, but this isn't something that mdformat can or should make. Adding angle brackets will change rendered HTML so is not a matter of style but content. You'll have to add the brackets manually unfortunately.

**Comment by jamesquilty** [comment]
How do you imagine manual changes will be made when mdl runs automatically in a CI pipeline?

**Comment by hukkin** [comment]
I don't think this is something that can safely be automated. There's no way for mdformat to tell which whether you want the angle brackets or not, and as I mentioned, it isn't a matter of style, Markdown AST and rendered HTML is different.

**Comment by jamesquilty** [comment]
I'm suggesting that this be a configurable option with the _status quo_ remaining as the default. It's obvioulsy safe to apply configured behaviours automatically.

This _is_ a matter of style, as fully described in [MD034](https://github.com/markdownlint/markdownlint/blob/master/docs/RULES.md#md034---bare-url-used). The _point_ of style rule MD034 is to achieve consistent HTML output no matter which renderer was used; the point is to change the Markdown source to achieve that. I happen to agree with that style rule, and I think it's fair to say that it's highly likely that many other people do also.

I'd prefer to not discuss the merits of this suggestion in a closed bug, I trust you appreciate that I have no choice or power in that respect.

**Comment by hukkin** [comment]
> This is a matter of style

It's not however. The renderings are visually different.

> The point of style rule MD034 is to achieve consistent HTML output no matter which renderer was used

Mdformat is a CommonMark compatible formatter. It doesn't care non compliant renderers.

> I happen to agree with that style rule, and I think it's fair to say that it's highly likely that many other people do also.

I also agree with it but only because it is the _only_ way to make an autolink in CommonMark. Without the angle brackets it's not an autolink. Again this is not a matter of style. Mdformat has no way of knowing if someone actually doesn't want an autolink. So you'll need to add the brackets manually.

> I'd prefer to not discuss the merits of this suggestion in a closed bug

I'm sorry you feel that way, but the suggestion goes around the [documented fundamentals of mdformat](https://mdformat.readthedocs.io/en/stable/users/style.html#formatting-style), so it's a very clear case for me, whether configurable or not.

**Comment by hukkin** [comment]
Oh and btw I do encourage making a plugin that does this, that's exactly what the plugin API is there for. I can also answer questions regarding plugin development. Essentially you'll need to override the renderer for `text` elements, use a link detection library (`linkify-it-py`) to detect links and add the brackets to convert to an autolink.

**Comment by jamesquilty** [comment]
Thanks, that looks promising and I'll give it a try as soon as I can. Packaging this along with the other configuration options I've drafted would create a coherent plugin.
