### ISSUE TITLE
ImportError: cannot import name 'unescape_string' from 'markdown_it.common.normalize_url'

### ISSUE THREAD

**Issue by cs-klaviyo** [executablebooks/mdformat#285]
### Describe the problem

Seeing mdformat fails locally with this trace:

```
File "....../python3.7/site-packages/mdformat/plugins.py", line 8, in <module>

    from mdformat.renderer import MDRenderer

  File "....../python3.7/site-packages/mdformat/renderer/__init__.py", line 7, in <module>

    from markdown_it.common.normalize_url import unescape_string

ImportError: cannot import name 'unescape_string' from 'markdown_it.common.normalize_url' (....../python3.7/site-packages/markdown_it/common/normalize_url.py)
```

Seems related to this recent markdown-it commit: https://github.com/executablebooks/markdown-it-py/commit/bb6cf6ecc545cf587357794cd340cc2207aa9688#diff-cdbaf938c7739a949222929740dd46fb5fb80c839b68c143f056d049592a2a52

### Steps to reproduce

Run a command like `pre-commit run mdformat --files some_file.md`

Seems to fail regardless of content.

### The version of Python you're using

3.7.7

**Comment by cs-klaviyo** [comment]
Following up, looks like this resolved itself with a `mdformat` upgrade (as I see markdown-it was pinned to < 2). I guess could be something to look out for.

**Comment by hukkin** [comment]
Thanks for the issue!

I believe this only happens when `markdown-it-py` v2 is installed and as you mention, we already have a pin in place to restrict to version <2 so I'll close this.

https://github.com/executablebooks/mdformat/pull/286 will bring compatibility with `markdown-it-py` v2.
