### ISSUE TITLE
Add more helpful debugging information when failing to parse code blocks

### ISSUE THREAD

**Issue by deenine** [executablebooks/mdformat#291]
### Description / Summary

When running Mdformat across a large documentation set, it would be very useful to know which file a given error message refers to. For example:

```
mdformat docs/
Warning: Failed formatting content of a json code block (line 435 before formatting)
Warning: Failed formatting content of a json code block (line 717 before formatting)
Warning: Failed formatting content of a json code block (line 857 before formatting)
Warning: Failed formatting content of a json code block (line 93 before formatting)
Warning: Failed formatting content of a json code block (line 210 before formatting)
Warning: Failed formatting content of a json code block (line 254 before formatting)
Warning: Failed formatting content of a json code block (line 301 before formatting)
Warning: Failed formatting content of a json code block (line 60 before formatting)
Warning: Failed formatting content of a json code block (line 118 before formatting)
Warning: Failed formatting content of a json code block (line 213 before formatting)
```

The above errors are due to invalid json blobs in 4 markdown documents in a documentation set of 122 markdown documents, fixing the json is a challenge without knowing which files to look at. 

### Value / benefit

Knowing which files are causing the warnings would enable the user to quickly and easily identify the code block that is causing the warning, and resolve (or ignore) it as appropriate. 

### Implementation details

I see a couple of options to implement this:

# Option 1: Verbose argument
The least code churn would be to add a ``--verbose` argument which prints the `path` in the `for path in file_paths:` loop in [`_cli.py`](https://github.com/executablebooks/mdformat/blob/master/src/mdformat/_cli.py#L58).

This gives the user the information they need, but prints a whole lot of information they don't need too (file paths that did not cause a warning) and requires the user to configure Mdformat to operate in verbose mode just to find the location of the warning, which is suboptimal if it is normally run as a pre-commit hook or via CI/CD.

# Option 2: Expand the warning output
The best option for ux is to update the output in [_context.py](https://github.com/executablebooks/mdformat/blob/master/src/mdformat/renderer/_context.py#L163) from:

`Warning: Failed formatting content of a json code block (line 435 before formatting)`

to something like:

`Warning: Failed formatting content of a json code block (line 435 before formatting) in: ./docs/badly_formed_json.md`

This appears to require the adding the filepath to the context

**Comment by hukkin** [comment]
Thanks for the issue!

Yeah something like Option 2 is the way to go here IMO. One thing to note is that there isn't always a file: it is possible that we are using mdformat Python API or that we are formatting standard input stream. We need to make sure the warning is sensible in these cases too.

**Comment by hukkin** [comment]
Option 2 was implemented and will be there in the next release after v0.7.13.

**Comment by deenine** [comment]
thanks @hukkin
