### ISSUE TITLE
New release 0.7.12 wants 4 spaces infront of `<br/>` 

### ISSUE THREAD

**Issue by PhilipMay** [executablebooks/mdformat#296]
### Describe the problem

I have a README.md which has something like this:

```
text
<br/>
text
```

For some reason the new release of mdformat now wants to add 4 spaces infront of the `<br/>`.
This breaks all my build pipelines. Since I see no reason why there must be 4 spaces I would say this is a bug.

Could you please patch this and make a patch release?

Many thanks
Philip

### Link to your repository or website

https://github.com/telekom/HPOflow/blob/main/README.md

### Steps to reproduce

see above

### The version of Python you're using

3.9

### Your operating system

Linux

**Comment by PhilipMay** [comment]
see https://github.com/telekom/HPOflow/runs/4746269968?check_suite_focus=true

**Comment by hukkin** [comment]
Ah damn. Thank you very much for the issue!

This change was made to avoid converting inline HTML elements to block HTML. For instance:
```markdown
text
<div>
text
```
is very different from
```markdown
text
    <div>
text
```

In the former there is a block HTML element and the two "text"s are not in the same paragraph. In the latter there is only one paragraph with an inline HTML element inside.

It seems that the `<br/>` behaves differently to `<div>` though. It is never interpreted as block HTML, in contrast to a `<div>` element, the spaces are not necessary. I've got to read the CommonMark spec a bit.

**Comment by hukkin** [comment]
If there's something positive here, it's that the issue is purely cosmetic and doesn't change rendered HTML in any way.

**Comment by PhilipMay** [comment]
> If there's something positive here, it's that the issue is purely cosmetic and doesn't change rendered HTML in any way.

Yes, but could you please somehow revert this behavior again?

**Comment by hukkin** [comment]
Yeah I'll try to come up with a fix during the weekend: hopefully a proper one that catches all cases, but if not, at least quick hack that targets this case precisely.

I do recommend using a version pin in CI, as suggested by mdformat docs. Although this is an unintended regression, it is possible some formatting style changes on purpose in the future.

**Comment by PhilipMay** [comment]
Thanks!

**Comment by PhilipMay** [comment]
> I do recommend using a version pin in CI, as suggested by mdformat docs. Although this is an unintended regression, it is possible some formatting style changes on purpose in the future.

Right. But I still want to serve as a regression tester for your cool tool. :-)

**Comment by hukkin** [comment]
Haha, that is an acceptable excuse.

The fix should be released on PyPI as soon as CI is finished here https://github.com/executablebooks/mdformat/pull/298
