### ISSUE TITLE
Improve compatibility with DocToc action

### ISSUE THREAD

**Issue by mdeweerd** [executablebooks/mdformat#310]
### Describe the problem/need and solution

**Context**
Use https://github.com/marketplace/actions/toc-generator and mdformat "together".

**Problem / Idea**
```
<!-- START doctoc generated TOC please keep comment here to allow auto update -->
<!-- param::isNotitle::true:: -->
<!-- param::maxHeaderLevel::4:: -->

<!-- DON'T EDIT THIS SECTION, INSTEAD RE-RUN doctoc TO UPDATE -->
<!-- END doctoc generated TOC please keep comment here to allow auto update -->
```

changes to

```
 <!-- START doctoc generated TOC please keep comment here to allow auto update -->

 <!-- param::isNotitle::true:: -->

 <!-- param::maxHeaderLevel::4:: -->
```

And the options are no longer used by doctoc in this action and disappear.

**Solution**
This could be fixed by skipping that section/adding a method to skip sections.

**Benefit**
This allows automatic TOC generation while keeping the DocToc options.

**Comment by hukkin** [comment]
Thanks for the issue!

I'm hesitant to add special casing like this. I'd suggest one of the following first
- Use [mdformat-toc](https://github.com/hukkin/mdformat-toc) to generate ToC with mdformat instead (my experience is that [doctoc can be a bit buggy](https://github.com/ethereum/consensus-specs/pull/2291#discussion_r604368567))
- Open an issue in https://github.com/thlorenz/doctoc and ask if they'd be able to ignore the added newline.

**Comment by mdeweerd** [comment]
+ Thanks for your reply & hint.

**Comment by hukkin** [comment]
> a feature to exlude part of the md file formatting could "fix" this

An issue for this exists: https://github.com/executablebooks/mdformat/issues/53

> Thanks for your reply & hint.

You're welcome! Please close this issue if mdformat-toc solves your issue
