### ISSUE TITLE
mdformat breaks mkdocs material admonitions

### ISSUE THREAD

**Issue by jmgilman** [executablebooks/mdformat#319]
### Describe the bug

**context**
When I format a file using [admonitions from mkdocs material](https://squidfunk.github.io/mkdocs-material/reference/admonitions/), they are automatically formatted in a broken way by `mdformat`. 

**expectation**
I expected `mdformat` to not format the admonition block.

**bug**
But instead, it tries to wrap all of the text together, breaking the admonition integration.

**problem**
This is a problem for people who rely on admonitions and still want to be able to format their documents. As far as I can tell there's no way to disable this behavior other than excluding files with admonitions (which are many in my case). 

### Reproduce the bug

Example admonition:

```markdown
!!! warning
   Some warning message
```

It gets reformatted to:

```markdown
!!! warning some warning message
```

### List your environment

```
$ python --version
Python 3.10.2
$ mdformat --version
mdformat 0.7.13 (mdformat_tables: 0.4.1)
```

**Comment by hukkin** [comment]
Thanks for the issue!

Closing in favor of https://github.com/executablebooks/mdformat/issues/309
