### ISSUE TITLE
Links should not be "resolved"

### ISSUE THREAD

**Issue by chrisjsewell** [executablebooks/mdformat#32]
Hmm, this is interesting. 
Running mdformat on:

```markdown
# mdformat-tables

[![Build Status][ci-badge]][ci-link]
[![codecov.io][cov-badge]][cov-link]
[![PyPI version][pypi-badge]][pypi-link]

An [mdformat](https://github.com/executablebooks/mdformat) plugin for rendering tables.

[ci-badge]: https://github.com/executablebooks/mdformat-tables/workflows/CI/badge.svg?branch=master
[ci-link]: https://github.com/executablebooks/mdformat/actions?query=workflow%3ACI+branch%3Amaster+event%3Apush
[cov-badge]: https://codecov.io/gh/executablebooks/mdformat-tables/branch/master/graph/badge.svg
[cov-link]: https://codecov.io/gh/executablebooks/mdformat-tables
[pypi-badge]: https://img.shields.io/pypi/v/mdformat-tables.svg
[pypi-link]: https://pypi.org/project/mdformat-tables
```

goes to

```markdown
# mdformat-tables

[![Build Status](https://github.com/executablebooks/mdformat-tables/workflows/CI/badge.svg?branch=master)](<https://github.com/executablebooks/mdformat/actions?query=workflow%3ACI+branch%3Amaster+event%3Apush>)
[![codecov.io](https://codecov.io/gh/executablebooks/mdformat-tables/branch/master/graph/badge.svg)](<https://codecov.io/gh/executablebooks/mdformat-tables>)
[![PyPI version](https://img.shields.io/pypi/v/mdformat-tables.svg)](<https://pypi.org/project/mdformat-tables>)

An [mdformat](<https://github.com/executablebooks/mdformat>) plugin for rendering tables.
```

I'd say that's not ideal behaviour 😬

If not in "core", I think we at least want a plugin that can "inhibit" this type of behaviour.

**Comment by chrisjsewell** [comment]
this is achievable I think, but would likely require overriding https://github.com/executablebooks/markdown-it-py/blob/master/markdown_it/rules_inline/link.py and https://github.com/executablebooks/markdown-it-py/blob/master/markdown_it/rules_inline/image.py, to output a new/special token type.
Then the easiest thing for the references, might be to dump them all at the end of the document.

**Comment by hukkinj1** [comment]
> I'd say that's not ideal behaviour :grimacing:

This is a bit loosely held opinion at this point, but I'm not sure I agree with this. Mdformat is an opinionated formatter, and this is a case where there are two structures that render to equal HTML. Mdformat has the opinion that inline links are better than reference links.

If theres a good argument to be made for mixing up these two styles, we could ofc consider changing this behavior.

> this is achievable I think, but would likely require overriding...

I'm not 100% sure but I think a plugin might be possible without any changes to parsing, due to the fact that plugins have access to the `env` dict (and `env["references"]`). If a reference exists there then a link can probably be assumed to be a reference link.

> Then the easiest thing for the references, might be to dump them all at the end of the document.

Agree with this.

**Comment by chrisjsewell** [comment]
> Mdformat has the opinion that inline links are better than reference links.

Why, what's the reasoning? I'm pretty sure this was not a pre-determined opinion 😜 

> I think a plugin might be possible without any changes to parsing,

No it definitely is; you have to override behaviour in links/images to auto-replace references during parsing

**Comment by hukkinj1** [comment]
> Why, what's the reasoning? I'm pretty sure this was not a pre-determined opinion

I couldn't think of a reason why one of these styles would hugely superior to the other. So had to pick one, and inline links I believe are used more and were a lot easier to implement. This "opinion" is documented in the readme, it's not there purely by accident.

> No it definitely is; you have to override behaviour in links/images to auto-replace references during parsing

I'm probably misunderstanding something, but aren't these auto-replaced references still in the `env` dict, even though not in the token stream?

**Comment by chrisjsewell** [comment]
Ah I missed that bullet point, my bad.
But I would say references are superior, since

(a) they reduce duplication
(b) they make the document more readable

for example this:

```markdown
[mdformat] ... [mdformat] ... [mdformat]

| a          | b          |
| ---------- | ---------- |
| [mdformat] | [mdformat] |

[my-ref]: https://github.com/executablebooks/mdformat
```

rather than this

```markdown
[mdformat](https://github.com/executablebooks/mdformat) ... [mdformat](https://github.com/executablebooks/mdformat) ... [mdformat](https://github.com/executablebooks/mdformat)

| a                                                       | b                                                       |
| ------------------------------------------------------- | ------------------------------------------------------- |
| [mdformat](https://github.com/executablebooks/mdformat) | [mdformat](https://github.com/executablebooks/mdformat) |
```

> but aren't these auto-replaced references

ah yeh so possibly re-replacing the references during rendering. That could work

**Comment by chrisjsewell** [comment]
the point is that they were included in CommonMark for a reason, and using mdformat should not preclude their use

**Comment by chrisjsewell** [comment]
Oh and as discussed in #33, this minimises diffs, if you need to change the href 😉

**Comment by chrisjsewell** [comment]
> re-replacing the references during rendering

The one "compromise" here, is that references are stored like:

```python
env["references"] = {
  "label1": {"href": "myhref1", "title": "my title", "map": [0, 1]},
  "label2": {"href": "myhref2", "title": "my title", "map": [2, 3]},
  "label3": {"href": "myhref2", "title": "my other title", "map": [4, 5]}
}
```

To re-instate them during rendering, you would need to translate this mapping to use `href` as the key, since link/image tokens do not store the original label.

```python
env["references"] = {
  "myhref1": {"label": "label1", "title": "mytitle", "map": [0, 1]},
  "myhref2": {"label": "label2", "title": "mytitle", "map": [2, 3]},
}
```

as you see, in this example we have now lost one of the original references.

Perhaps this is good, in that there should only be unique mappings of label -> href, but the corner-case (as shown) is if they had different titles.

**Comment by chrisjsewell** [comment]
> since link/image tokens do not store the original label

I could cheat and add an option in markdown-it-py, for these labels to be stored in the tokens.
This would be a deviation to the JS code, but hey its my package, so my perogative 😄

**Comment by hukkinj1** [comment]
Yeah I'm starting to think we want to support ref links too.

> the point is that they were included in CommonMark for a reason, and using mdformat should not preclude their use

This isn't a very good point though. Formatters by definition work in a way where they preclude the use of some style related syntax. If a formatter does not make any of these decisions, then it's just a text passthrough function like `lambda x: x`.
