### ISSUE TITLE
Consecutive numbered lists

### ISSUE THREAD

**Issue by chrisjsewell** [executablebooks/mdformat#33]
I can see the thinking for using `1.` for all numbered list items; with a renderer handling proper numbering.
However, one of the benefits of Markdown is that it is easily readable without the need for rendering.
This is diminished with this sort of (non-)numbering, and I bet most people would opt for consecutive numbering, if given the choice.

I would say there should at least be the option (if not in "core" then *via* a plugin) to achieve this.

**Comment by hukkinj1** [comment]
For me some of the objectives/goals in mdformat development have been (heavily inspired by e.g black) (maybe I should write something in the contribution guide about this):
- mdformat attempts to minimize diffs
- mdformat is opinionated so you don't have to be
- no configuration unless a very good reason

This (non-)numbering style was done on purpose to minimize diffs. Lets say I'm listing the alphabets, using a style where list items are correctly numbered:

```markdown
1. b
2. c
3. d
```

I then notice I forgot the character "a" and add it as first item in the list. As a result, the numbering of every subsequent item in the list will change, meaning that the diff will touch every line in the list. The non-numbering style solves this issue: only the added line will show up in the diff.

In this case the style comes at the cost of some readability. The nice thing about Markdown is, as you mentioned, if we really need it to be readable, we can always render the HTML.

So with all this in mind:
- the default non-numbering style won't change
- I'm a bit reluctant still :smiley: , but this could be one of the exceptions where adding configuration to "core" might be ok
- a plugin that does numbering should be quite straightforward to implement with the current plugin API already

**Comment by chrisjsewell** [comment]
thanks for the explanation, yep I didn't consider the "minimize diffs" argument, which is an interesting point.
Those goals should definitely be documented 👍

**Comment by hukkinj1** [comment]
I considered this a bit. I'd be willing to merge a CLI flag that changes the style to consecutive numbering. The default style will remain the same though.

**Comment by chrisjsewell** [comment]
should be easy to add once #35 is merged
