### ISSUE TITLE
Formatted Markdown renders to different HTML than the input (unknown why)

### ISSUE THREAD

**Issue by hpux735** [executablebooks/mdformat#338]
### Describe the bug

**context**

When I run mdformat on my markdown file, I get the following:

```
Error: Could not format "-".

The formatted Markdown renders to different HTML than the input Markdown. This
is likely a bug in mdformat. Please create an issue report here, including the
input Markdown: https://github.com/executablebooks/mdformat/issues
```

I'm editing a document from an open source project, and they use mdformat, so I suspect it's related to my changes, but I can't tell why.  Is there a way to force mdformat to emit the formatted markdown so I can 'diff' it?  An example of the kind of changes I've made are included below:

````

<div class="tabbed-blocks">

```python
(
    df.lazy()
    .filter(pl.col("sepal_length") > 5)
    .groupby("species")
    .agg(pl.all().sum())
    .collect()
)
```

```rust,noplayground
let df = df
    .lazy()
    .filter(col("sepal_length").gt(5))
    .groupby([col("species")])
    .agg([col("*" ).sum()])
    .collect()?;
```
</div>

````

I've added the `<div>` tags and the second code block.  This renders in the book as a tabbed code block that lets you select which language you want to see.  Formerly, it was just Python.

**expectation**

I expected mdformat to format the markdown in a non-changing way.  And, failing that, tell me what changes were made.  Maybe when this bug happens you could run both copies into `diff` so that we can have a clue what happened?  This way we might be able to come up with workarounds on our own?

**bug**

The formatted markdown apparently renders to different html than input.

```
Error: Could not format "-".

The formatted Markdown renders to different HTML than the input Markdown. This
is likely a bug in mdformat. Please create an issue report here, including the
input Markdown: https://github.com/executablebooks/mdformat/issues
```

**problem**

This is a problem because the upstream project runs mdformat in CI, and the jobs are failing.

### Reproduce the bug

`mdformat into.md`

[intro.md](https://github.com/executablebooks/mdformat/files/9331782/intro.md)

### List your environment

```
mdformat --version
mdformat 0.7.5

macos 12.4

python 3.10.4
```

**Comment by hukkin** [comment]
Hi, thanks for the issue!

You're running a relatively old mdformat version. I recommend trying with the latest release.

The snippet you provided seems to format fine with mdformat versions 0.7.5 and 0.7.14. Would you be able to provide me with full unedited/uncut input so that I can reproduce the error?

>  Is there a way to force mdformat to emit the formatted markdown so I can 'diff' it?

Currently no, unfortunatley. There's an open issue for this though.

**Comment by hpux735** [comment]
Sure enough!  I updated the requirements.txt for the project and it seems to be addressed.  Thanks for checking!
