### ISSUE TITLE
--wrap removes unicode spaces

### ISSUE THREAD

**Issue by nschloe** [executablebooks/mdformat#339]
### Describe the bug

The following markdown as an [em space] between the two x:
```markdown
em-space: x x
```
running
```
mdformat --wrap 100 a.md
```
on the file incorrectly transforms the em-space into a regular space. The problem does not occur without `--wrap`.

### Reproduce the bug

If it helps,

```
open("b.md").read()
```

in IPython shows the string with Unicode characters escaped.

### List your environment

- Python 3.10.6
- Ubuntu 22.10

**Comment by hukkin** [comment]
Thanks a lot for the issue!

https://github.com/executablebooks/mdformat/pull/341 should fix this. I plan to make a release in the upcoming days.

**Comment by nschloe** [comment]
Cool, thanks!
