### ISSUE TITLE
format failure with non-breaking space

### ISSUE THREAD

**Issue by nschloe** [executablebooks/mdformat#351]
### Describe the bug

When running mdformat on
```markdown
a

 

b
```
it'll fail. Note the non-breaking space in the middle, i.e.,
```python
"a\n\n\xa0\n\nb"
```

### Reproduce the bug

See above.

**Comment by hukkin** [comment]
Thanks for the issue! Let's get this fixed.

In the meanwhile, you can simply remove the NBSP manually. It has no effect on rendered HTML here.

I'm curious to know what you run mdformat against to provide me with these great test cases? :smile:

**Comment by nschloe** [comment]
> I'm curious to know what you run mdformat against to provide me with these great test cases?

I'm compiling articles from arxiv.org to markdown, and you wouln't believe what constructs you find there. :smile: 

> In the meanwhile, you can simply remove the NBSP manually.

NBSP have a meaning in most cases and I need to preserve them.

**Comment by hukkin** [comment]
Cool!

> NBSP have a meaning in most cases and I need to preserve them.

That is correct. But in this particular case all that the NBSP does is it makes an empty `<p></p>` element which [user agents should ignore](https://www.w3.org/TR/REC-html40/struct/text.html#edef-P).
