### ISSUE TITLE
Do not update the timestamp of the files when they are left unchanged

### ISSUE THREAD

**Issue by paugier** [executablebooks/mdformat#357]
### Describe the bug

mdformat updates the timestamp of the files even when they are left unchanged. Instead, mdformat should not touch files when they are left unchanged (as `black` does for example).

### Reproduce the bug

Use stat and mdformat on one well formatted file.

**Comment by hukkin** [comment]
Thanks for the issue and the PR!

I agree we should change this. I hope I'll have the time to review the PR soon. :smile_cat:
