### ISSUE TITLE
Option to keep tokens unchanged

### ISSUE THREAD

**Issue by holamgadol** [executablebooks/mdformat#370]
### Context

I'm developing a tool to get some markdown file, render it to AST (or _tokens_ in _markdown_it_ terms), edit AST and render back to markdown.

MWE for my purposes:
```python
from markdown_it import MarkdownIt
from mdformat.renderer import MDRenderer

md = MarkdownIt("commonmark")

source_markdown = """
Here's some *text*

1. a list

> a *quote*"""

tokens = md.parse(source_markdown)

renderer = MDRenderer()
options = {}
env = {}

output_markdown = renderer.render(tokens, options, env)
```

It works, but sometimes I need to keep my tokens untouched and just render a markdown without formatting. For example, I don't want to escape symbols like `[]` and `<>`, because I need to use them in the following markdown file transformations.

### Proposal

My idea is to introduce a new option `keep_original`, which can behave similarly like this:

```python
def text(node: RenderTreeNode, context: RenderContext) -> str:
    """Process a text token.

    Text should always be a child of an inline token. An inline token
    should always be enclosed by a heading or a paragraph.
    """
    text = node.content
    if context.options.get("keep_original", False):
        return text
```

Another variant is to allow users to override functions in `/mdformat/renderer/_context.py` via public API.

**Comment by hukkin** [comment]
You seem to want a style-preserving formatter. For this to happen, you'd need the underlying Markdown parser to store concrete syntax, with all style information included, which it doesn't.

> For example, I don't want to escape symbols like [] and <>, because I need to use them in the following markdown file transformations.

Note that mdformat doesn't escape the symbols you mention to "add formatting" or change the tokens, quite the opposite. It does so to make sure the abstract syntax and tokens are preserved in rendered Markdown, in all cases.

> Another variant is to allow users to override functions in /mdformat/renderer/_context.py via public API.

You can do this with a plugin https://mdformat.readthedocs.io/en/stable/contributors/contributing.html#developing-parser-extension-plugins

**Comment by holamgadol** [comment]
> You can do this with a plugin
Thanks, I'll try it with a plugin then
