### ISSUE TITLE
inconsistent indenting of nested lists

### ISSUE THREAD

**Issue by afeld** [executablebooks/mdformat#371]
### Describe the bug

**context**
When I run MdFormat on [this notebook](https://github.com/afeld/python-public-policy/blob/27117d064fee94d6d0d3c4f7a34ff64c9799e62a/hw_0.ipynb) through [nbqa](https://nbqa.readthedocs.io/)…

**expectation**
I expected to get nested lists indented a certain number of spaces.

**bug**
But instead some are indented two spaces, while some are indented three.

```diff
diff --git hw_0.ipynb hw_0.ipynb
index 4aaa010..ef99e82 100644
--- hw_0.ipynb
+++ hw_0.ipynb
@@ -11,16 +11,16 @@
     "Kaggle, like JupyterHub and Google Colab, is built around Jupyter notebooks. They are not _exactly_ the same, but will feel similar. For this homework
:\n",
     "\n",
     "1. Do following Kaggle [Learn Python](https://www.kaggle.com/learn/python) tutorials and exercises. You do not need to turn these in.\n",
-    "    - [Hello, Python](https://www.kaggle.com/colinmorris/hello-python)\n",
-    "    - [Booleans and Conditionals](https://www.kaggle.com/colinmorris/booleans-and-conditionals)\n",
-    "    - [Strings and Dictionaries](https://www.kaggle.com/colinmorris/strings-and-dictionaries)\n",
+    "   - [Hello, Python](https://www.kaggle.com/colinmorris/hello-python)\n",
+    "   - [Booleans and Conditionals](https://www.kaggle.com/colinmorris/booleans-and-conditionals)\n",
+    "   - [Strings and Dictionaries](https://www.kaggle.com/colinmorris/strings-and-dictionaries)\n",
     "1. Read about:\n",
-    "    - [Tuples, lists, and dictionaries](http://sthurlow.com/python/lesson06/)\n",
-    "    - [Errors and exceptions](https://swcarpentry.github.io/python-novice-inflammation/09-errors/index.html)\n",
+    "   - [Tuples, lists, and dictionaries](http://sthurlow.com/python/lesson06/)\n",
+    "   - [Errors and exceptions](https://swcarpentry.github.io/python-novice-inflammation/09-errors/index.html)\n",
     "1. Do the coding challenges below.\n",
     "1. Do the following Kaggle tutorials and exercises. You do not need to turn these in.\n",
-    "    - [Python Lists](https://www.kaggle.com/colinmorris/lists)\n",
-    "    - [Creating, Reading, and Writing with Pandas](https://www.kaggle.com/residentmario/creating-reading-and-writing)\n",
+    "   - [Python Lists](https://www.kaggle.com/colinmorris/lists)\n",
+    "   - [Creating, Reading, and Writing with Pandas](https://www.kaggle.com/residentmario/creating-reading-and-writing)\n",
     "1. Post a question, per the instructions at the bottom.\n",
     "1. [Turn in this notebook.](https://python-public-policy.afeld.me/en/latest/README.html#turning-in-assignments)\n",
     "\n",
@@ -163,8 +163,8 @@
     "We will now make an interactive tool to assess people for unemployment benefits. We will use a simplified version of [the rules from the New York Stat
e Department of Labor](https://www.labor.ny.gov/formsdocs/ui/TC318.3e.pdf#page=18), as follows. To be elegible, one must:\n",
     "\n",
     "- Have lost employment\n",
-    "- Have made at least $10,000 in the past year\n",
-    "    - Ask for their salary rather than as a yes-or-no question\n",
+    "- Have made at least \\$10,000 in the past year\n",
+    "  - Ask for their salary rather than as a yes-or-no question\n",
     "- Be ready, willing and able to work immediately\n",
     "- Be actively seeking work\n",
     "\n",
```

**problem**
This is a problem because I'm publishing that notebook via [JupyterBook](https://jupyterbook.org/), and it's Markdown parser only seems to support nested lists indented 3+ spaces.

cc https://github.com/executablebooks/mdformat/issues/331#issuecomment-1224279288 for the option to make that configurable for more fragile Markdown parsers

### Reproduce the bug

1. Download [this notebook](https://github.com/afeld/python-public-policy/blob/27117d064fee94d6d0d3c4f7a34ff64c9799e62a/hw_0.ipynb)
2. Run Mdformat through [nbqa](https://nbqa.readthedocs.io/):

   ```sh
   nbqa mdformat hw_0.ipynb --nbqa-md
   ```

### List your environment

```
$ jupyter-book --version
Jupyter Book      : 0.13.1
External ToC      : 0.2.4
MyST-Parser       : 0.15.2
MyST-NB           : 0.13.2
Sphinx Book Theme : 0.3.3
Jupyter-Cache     : 0.4.3
NbClient          : 0.5.13
$ nbqa --version
nbqa 1.5.3
$ mdformat --version
mdformat 0.7.16 (mdformat_myst: 0.1.5, mdformat_tables: 0.4.1, mdformat_frontmatter: 0.4.1)
```

**Comment by hukkin** [comment]
> But instead some are indented two spaces, while some are indented three.

The logic here is as follows:
- mdformat always indents unordered lists with two spaces
- indent width of ordered lists depends on the width of the initial number of the ordered list
  ```markdown
  1. Here indent width is
     three.

  123. Here indent width is
       five. It needs to be so, because

       Otherwise this next paragraph doesn't belong in the same list item.
  ``` 

> This is a problem because I'm publishing that notebook via [JupyterBook](https://jupyterbook.org/), and it's Markdown parser only seems to support nested lists indented 3+ spaces.

Hmm, are you 100% sure about this? I'm doubtful, because JupyterBook uses [myst-nb](https://github.com/executablebooks/jupyter-book/blob/821e910826a05798daca105ebea435892754f6c3/pyproject.toml#L36) which uses [myst-parser](https://github.com/executablebooks/MyST-NB/blob/385c4a7afb3a377486c1aa7a86b4c8a0e93484f5/pyproject.toml#L42) which uses [markdown-it-py](https://github.com/executablebooks/MyST-Parser/blob/c2f041632825ffe9837ebdded4ed324d4288cfa7/pyproject.toml#L39) to parse Markdown, and that is a CommonMark compliant parser which happens to be the same exact parser used by mdformat.

**Comment by KyleKing** [comment]
I published [mdformat-mkdocs](https://github.com/KyleKing/mdformat-mkdocs) to format list indents to 4-spaces, which might be helpful for your use case

**Comment by hukkin** [comment]
> This is a problem because I'm publishing that notebook via [JupyterBook](https://jupyterbook.org/), and it's Markdown parser only seems to support nested lists indented 3+ spaces.

Closing, as this issue should be fixed now by installing KyleKing's mdformat-mkdocs plugin.
