### ISSUE TITLE
Header of GitHub issue templates gets messed up

### ISSUE THREAD

**Issue by unparalleled-js** [executablebooks/mdformat#372]
### Describe the bug

**context**
When I run `mdformat`

**expectation**
I expected recognition of GitHub templates and to allow necessary formats to retain

**bug**
But instead GitHub issue templates get messed up headers

**problem**
This is a problem for people who have issue templates that they don't want messed up

### Reproduce the bug

Have template that starts like:

```
---
name: Bug report
about: Report an error that you've encountered.
labels: 'category: bug'
---
```

and it will auto-format it to:

```
______________________________________________________________________

## name: Bug report about: Report an error that you've encountered. labels: 'category: bug'
```

**Comment by hukkin** [comment]
Hi!

The syntax you use is not CommonMark.

Quoting the readme file:

> For full GitHub support do:
> ```sh
> pip install mdformat-gfm mdformat-frontmatter mdformat-footnote
> ```

**Comment by unparalleled-js** [comment]
This seems to work, except in pre-commit

**Comment by unparalleled-js** [comment]
I probably need to add the deps to the precommit somehow

**Comment by hukkin** [comment]
The example in the docs shows how to use plugins with pre-commit https://mdformat.readthedocs.io/en/stable/users/installation_and_usage.html?highlight=pre-commit#usage-as-a-pre-commit-hook

**Comment by gwpl** [comment]
regarding `pip install mdformat-gfm mdformat-frontmatter mdformat-footnote`

just FYI how users may find your application. 

I found is in AUR:

https://aur.archlinux.org/packages/mdformat

and that's how I installed it. So maybe good to add those other binaries there into software packages by default. 🤷🏻  - just idea 💡
