### ISSUE TITLE
Document a new plugin for shorter thematic breaks

### ISSUE THREAD

**Issue by csala** [executablebooks/mdformat#376]
### Context

I am using `mdformat` but having troubles with the current thematic break rendering composed of 70 underscore characters, which I am rather used to typing as three dashes `---`.

My (very personal and opinionated) reasons being:
1. The default `vim` highlighting for Markdown syntax breaks when multiple underscores are put together, because it conflicts with the italics format. Notice that this can probably be solved with Vim plugins or configuration tweaks, but the origin of the problem is about raw `vim` with no plugins.
2. Typing `---` while writing a document is quick and easy, while typing a line of exactly 70 underscores is comparatively much harder and needs some sort of copy/paste action. My usual coding workflow involves code style checkers like `mdformat` and `black` as `pre-commit` hooks, but in general I try to type in code and documentation that is already valid to minimize the number of times that these tools have to modify what I have typed, which forces me to redo the review, `git add` and `pre-commit` loop.

I admit that these are very personal reasons, so I do not wish to engange in any discussions about [the current rendering  style and the rationale behind it](https://mdformat.readthedocs.io/en/stable/users/style.html#thematic-breaks).

Instead, I thought best to take the route of coding a new plugin which overrides the rendering style for thematic breaks with three dashes, so anyone who wants can take advantage of it without having to do any change in the main `mdformat` project: https://github.com/csala/mdformat-simple-breaks

### Proposal

The proposal is just to add the plugin to the corresponding [list in the documentation](https://mdformat.readthedocs.io/en/stable/users/plugins.html#parser-extension-plugins)
I'm happy to make a PR for it.

### Tasks and updates

- [ ] Discuss and decide if a PR is wanted
- [ ] Do the corresponding PR

**Comment by hukkin** [comment]
A PR is very welcome! :smile_cat:

**Comment by hukkin** [comment]
Closing (https://github.com/executablebooks/mdformat/pull/418)
