### ISSUE TITLE
non-breaking space -> error

### ISSUE THREAD

**Issue by nschloe** [executablebooks/mdformat#390]
### Describe the bug

Running mdformat on
```
# X
 

x
```
(`# X\n\xa0\n\nx\n`, note the non-breaking space) results in the error message

```
The formatted Markdown renders to different HTML than the input Markdown. This
is likely a bug in mdformat. Please create an issue report here, including the
input Markdown: https://github.com/executablebooks/mdformat/issues
```

### Reproduce the bug

See above.

**Comment by hukkin** [comment]
Thanks for reporting!

It seems this was fixed by https://github.com/executablebooks/mdformat/pull/352 and released in mdformat 0.7.17
