### ISSUE TITLE
Support option to use `*` for bullet lists if preffered.

### ISSUE THREAD

**Issue by gwpl** [executablebooks/mdformat#392]
### Context

Original Daring Fireball specification https://daringfireball.net/ , allows `-` and `*` both for bullet lists.

This causes inconsistency, as some people use `-` some `*` (which `*` seems to look more like default in Daring Fireball specification).

### Proposal

Provide a flag that allow to canonicalize bullet lists  to either `*` or `-` according to preference of `mdformat` user.

**Comment by hukkin** [comment]
Hello and welcome!

Here's some of my thoughts on adding new conf options: https://github.com/executablebooks/mdformat/issues/283#issuecomment-978155862

I don't think Daring Fireball is a style guide, more like a spec, so don't think we should treat is as such. Also, mdformat supports CommonMark, not John Gruber's Markdown.

**Comment by brendanmaguire** [comment]
For anyone coming across this issue looking for a solution, I've created a plugin which allows you to configure this. https://pypi.org/project/mdformat-lists/
