### ISSUE TITLE
Consider respecting gfm checklists

### ISSUE THREAD

**Issue by gwpl** [executablebooks/mdformat#395]
### Describe the bug

Input:

```
* [ ] A
* [x] B
* [ ] C
```

output:

```
* \[ \] A
* \[x\] B
* \[ \] C
```

Those are GFM checklists, probably should stay intact.

### Reproduce the bug

snippets above with mdformat 0.7.16

**Comment by hukkin** [comment]
Hi!

Please see https://github.com/hukkin/mdformat-gfm/ and https://github.com/executablebooks/mdformat/issues/332

Closing in favor of https://github.com/executablebooks/mdformat/issues/332
