### ISSUE TITLE
Find out if image links need angle brackets

### ISSUE THREAD

**Issue by hukkinj1** [executablebooks/mdformat#40]
See https://github.com/executablebooks/mdformat/pull/38#issuecomment-699664927

- [ ] add tests
- [ ] surround image links with angle brackets if tests fail

**Comment by hukkinj1** [comment]
I've confirmed that the angle brackets are needed. Here's some test vectors that should be added to `test_renderer_correctness.py`:

- ```markdown
  ![link](<foo(and(bar)>)
  ```
- ```markdown
  ![link](foo\(and\(bar\))
  ```
- ```markdown
  ![link](foo\)\:)
  ```
- ```markdown
  ![a](<b)c>)
  ```

**Comment by chrisjsewell** [comment]
So is it just that `<>` need to be added if a link contains an internal `(` or `)`?
If so, would it be "nicer" formatting, if you only added `<>` when these were found in the link?

**Comment by hukkinj1** [comment]
From https://spec.commonmark.org/0.29/#links:
> A link destination consists of either
> - a sequence of zero or more characters between an opening < and a closing > that contains no line breaks or unescaped < or > characters,
> - or a nonempty sequence of characters that does not start with <, does not include ASCII space or control characters, and includes parentheses only if (a) they are backslash-escaped or (b) they are part of a balanced pair of unescaped parentheses. (Implementations may impose limits on parentheses nesting to avoid performance issues, but at least three levels of nesting should be supported.)

I don't have a strong preference regarding the style. Without the brackets could be "nicer", but with the brackets it's simpler formatting logic and the links will always look the same (this can sometimes be handy for grepping, regexing etc a file). If you have a strong preference for "without the brackets" style, I will merge it.

Fixing the bug is a bigger priority for me, and should be easiest to implement by adding the brackets.

**Comment by chrisjsewell** [comment]
fair, something to add to explainer docs 😉
