### ISSUE TITLE
Checkboxes are escaped

### ISSUE THREAD

**Issue by sanmai-NL** [executablebooks/mdformat#401]
### Describe the bug

**context**

```markdown
1. [ ] …
```

**expectation**

```markdown
1. [ ] …
```

**bug**

```markdown
1. \[ \] …
```

**problem**
This is a problem for people using GitHub-flavored Markdown, e.g., for templates, since it renders the checkboxes unusable.

### Reproduce the bug

See previous section.

### List your environment

```
mdformat 0.7.16
```

**Comment by duongdominhchau** [comment]
I have the same issue, adding GFM plugin works. Try `pip install mdformat-gfm`
