### ISSUE TITLE
mdformat breaks Hugo shortcodes by escaping `<`

### ISSUE THREAD

**Issue by jamesbraza** [executablebooks/mdformat#402]
### Describe the bug

**context**

Running `mdformat` on a Markdown file with a Hugo shortcode.

**expectation**

I expected `mdformat` to not break the shortcode.

**bug**

Instead `mdformat` is breaking the shortcode by escaping `<` to `\<`.

**problem**

This breaks the shortcode for Hugo users.

Relevant Hugo comment: https://github.com/executablebooks/mdformat/issues/112#issuecomment-1148935498

### Reproduce the bug

```md
{{< youtube -dJolYw8tnk >}}
```

That links to [this YouTube video](https://youtu.be/-dJolYw8tnk).  `mdformat` corrects this to

```md
{{\< youtube -dJolYw8tnk >}}
```

### List your environment

```
mdformat==0.7.16
mdformat-frontmatter==2.0.1
```

**Comment by Oliver-Habersetzer** [comment]
I agree this can be annoying. Also "[" and "]" are escaped - so I can't use this for [Obsidian](https://obsidian.md). I might make a PR so we're able to configure this behavior.

**Comment by BartKeulen** [comment]
I just want to add another case. I am using [mkdocs](https://www.mkdocs.org/) with [PyMarkdown Extension Snippets](https://facelessuser.github.io/pymdown-extensions/extensions/snippets/); useful for embedding content directly in your documentation pages.

A document is included using the following syntax:

```markdown
--8<-- "filename.ext"
```

mdformat changes it to:

```markdown
--8\<-- "filename.ext"
```

The behavior does not happen inside a code block, the following code is not changed:

```markdown
\```yaml
--8<-- "filename.yml"
\```
```

(had to add the escape characters to display it kind of correctly, lol).

**Comment by ALizarazoTellez** [comment]
GitHub blocks highlights are escaped too: https://github.com/orgs/community/discussions/16925

Changes:
```markdown
> [!NOTE]
> Test
```

With:
```markdown
> \[!NOTE\] Test
```

**Comment by PythonFZ** [comment]
Any updates on this?

**Comment by mmcdermott** [comment]
It would be really nice to have support for turning off this escape option. Is there any progress on this?

**Comment by ecbaldwin** [comment]
For those looking for a work-around, I found one that works at least in my case. I don't love it but it enabled me to move on.

Surrounding the shortcode with an inline code block prevents mdformat from escaping anything inside it. The surprising thing to me is the precedence of the shortcode is apparently higher than the precedence of the code block. The side-effect is that there is an empty `<code></code>` rendered before the output of the shortcode. I was also surprised that the shortcode did not render ***inside*** the code block, and maybe this will break in some cases (or in the future).

```
 `{{< highlight-file "file.yaml" yaml "">}}`
```
