### ISSUE TITLE
Error: Could not format

### ISSUE THREAD

**Issue by seancolsen** [executablebooks/mdformat#413]
### Describe the bug

mdformat is unable to format a Markdown document I have.

### Reproduce the bug

1. Use this [README.md](https://github.com/centerofci/mathesar/blob/a29030c5c80e29941f524b44323dca947b07be6c/docs/README.md?plain=1) file.
1. Run `mdformat README.md`
1. Expect the document to be formatted
1. Instead, observe the following error:

    > Error: Could not format "/home/sean/cci/repo/mathesar/docs/README.md".
    > 
    > The formatted Markdown renders to different HTML than the input Markdown. This
    > is likely a bug in mdformat. Please create an issue report here, including the
    > input Markdown: https://github.com/executablebooks/mdformat/issues

### List your environment

- mdformat 0.7.17
- mdformat_mkdocs 1.0.4
- Python 3.10.12
- Ubuntu 22.04

**Comment by hukkin** [comment]
Thanks for the issue!

Vanilla mdformat has no trouble formatting your text. The issue seems to only occur with the externally developed plugin you use, mdformat_mkdocs. You should file an issue here https://github.com/KyleKing/mdformat-mkdocs/issues
