### ISSUE TITLE
Options to disable/enable rules

### ISSUE THREAD

**Issue by verhovsky** [executablebooks/mdformat#431]
### Context

I want to format a bunch of markdown files, but I don't want to apply all the rules, just one important rule.

For example, I have this in my frontmatter

```md
contributors:
    - ["First Last", "email@example.com"]
```

which is changing the indentation and removing the quotes around the name. I don't want this.

### Proposal

A syntax like https://github.com/markdownlint/markdownlint has for enabling/disabling rules

```sh
mdformat -r ~frontmatter *.md
```

**Comment by verhovsky** [comment]
I have it installed, that's why it's formatting the frontmatter.

**Comment by hukkin** [comment]
Closing as the feature isn't really doable as described here. We format based on parse results that are abstract syntax, so it's not really possible to cherry pick formatting rules while keeping the rest of the document unchanged.

Closest to this that I imagine would be doable is to enable/disable installed plugins (which unfortunately doesn't really solve this use case).
