### ISSUE TITLE
Wrapping of badge lines

### ISSUE THREAD

**Issue by LecrisUT** [executablebooks/mdformat#437]
### Describe the bug

**context**
I was adding badges in [this PR](https://github.com/cp2k/cp2k/pull/3367), and the project's pre-commit (which uses `mdformat`, don't know which version) was suggesting a change like:
```patch
- [![Release Status][release-badge]][release-link]
- [![Fedora Status][fedora-badge]][fedora-link]
+ [![Release Status][release-badge]][release-link] [![Fedora Status][fedora-badge]][fedora-link]                
[![Spack Status][spack-badge]][spack-link] 
```

Probably because `--wrap=100` is used.

**expectation**

For badge lines it would make more sense to keep them as individual lines to better support `git` navigation.

It would be nice to have a way to disable this formatting for specific sections. Like `# format: off`

### Reproduce the bug

`mdformat --wrap 100` on:
```markdown
[![Release Status][release-badge]][release-link]
[![Fedora Status][fedora-badge]][fedora-link]
[![Spack Status][spack-badge]][spack-link]

[fedora-badge]: https://img.shields.io/fedora/v/cp2k
[fedora-link]: https://src.fedoraproject.org/rpms/cp2k
[release-badge]: https://img.shields.io/github/v/release/cp2k/cp2k
[release-link]: https://github.com/cp2k/cp2k/releases
[spack-badge]: https://img.shields.io/spack/v/cp2k
[spack-link]: https://packages.spack.io/package.html?name=cp2k
```

**Comment by hukkin** [comment]
Hey, thanks for the issue!

This isn't really a bug. The set of inline images you have is a paragraph like any other, so will be wrapped if you ask mdformat to `--wrap` it. I think it's reasonable to not expect mdformat to know the concept of a badge line.

We could decide that wrapping doesn't happen if there are images only, but I'm not sure. Perhaps someone doesn't want that?

The current state is at least consistent from when looking at the CommonMark structure.

**Comment by hukkin** [comment]
Generally I do recommend not wrapping at all: https://mdformat.readthedocs.io/en/stable/users/style.html#paragraph-word-wrapping

**Comment by hukkin** [comment]
I'll actually close the issue because I don't want to special case this. We don't get concrete syntax from the parser, so changing the behavior would mean that if someone deliberately has multiple images on one line, then mdformat would force them on separate lines even though they did fit fine on that one line originally.
