### ISSUE TITLE
Configure default language for fenced code blocks

### ISSUE THREAD

**Issue by varac** [executablebooks/mdformat#438]
### Context

When reformatting indented code blocks, I'd like to have an option to set the default language added to the fenced code block that mdformat creates.
I habe a lot of old documentation with indeded code blocks, and 99% of them are `sh` lang, which I manually need to add after reformatting.

### Proposal

Add an option to the config file like: 

```toml
fenced_lang = sh
```

Which will automatically use 

    ```sh 

instead of 

    ```

when reformatting indented code blocks.

**Comment by hukkin** [comment]
Hey thanks for the issue!

I don't think this is a generally useful enough feature to be added. I think mdformat should be helpful to you anyways: run it to normalize all code blocks, and then it should be fairly trivial to come up with a `sed` script to add  the `sh` language tags.
