### ISSUE TITLE
Guidance on Extending mdformat Configurability

### ISSUE THREAD

**Issue by KyleKing** [executablebooks/mdformat#441]
### Context

There are a number of issues and open PRs to extend mdformat's configurablability for various use cases: #318, #381, #391, #412, #400, #438, #437, #432, #431, https://github.com/executablebooks/mdformat/issues/359#issuecomment-1255040071, #428, #421, https://github.com/executablebooks/mdformat/issues/268#issuecomment-921764673, #262, #234 (and https://github.com/executablebooks/mdformat-myst/pull/9#issuecomment-872536598), https://github.com/executablebooks/mdformat/issues/331#issuecomment-1168504476, #332, #378, https://github.com/executablebooks/mdformat/issues/53#issuecomment-705034415, https://github.com/executablebooks/mdformat/issues/283#issuecomment-978155862, https://github.com/executablebooks/mdformat/issues/261#issuecomment-980498732, #50, etc.

In a number of instances @hukkin has reiterated the position that mdformat should only support the minimum amount of configuration (https://github.com/executablebooks/mdformat/issues/283#issuecomment-978155862). The recommended alternative is for users to implement plugins in order to change behavior. In doing so, we should be sure to document where users have successfully demonstrated extending `mdformat` configuration through plugins (such as: https://github.com/executablebooks/mdformat/issues/356#issuecomment-1373814517)

### Proposal

There should be official documentation and/or guidance to clarify what kinds of configuration belong in mdformat vs. those that should be implemented as plugins. I believe this philosophy is strongly held and should be proactively communicated. PRs and issues should be reviewed and/or closed accordingly because some have been in limbo for years.

**Comment by hukkin** [comment]
Thanks for the issue Kyle!

> mdformat should only support the minimum amount of configuration

This is correct, and is one of the first things mentioned in the [contributing docs](https://mdformat.readthedocs.io/en/stable/contributors/contributing.html).

> The recommended alternative is for users to implement plugins in order to change behavior. In doing so, we should be sure to document where users have successfully demonstrated extending mdformat configuration through plugins

I've recently thought it may be best to _reduce_ the amount of plugins we refer to in the docs to just a few essential ones like `mdformat-gfm`, and make it very clear the list is non-comprehensive. Then point to https://github.com/topics/mdformat for more.

I can't guarantee the quality or maintenance status of plugins other people develop so probably best not to "bless" any of them, or set false expectations of the comprehensiveness of the manually maintained plugin list.

> There should be official documentation and/or guidance to clarify what kinds of configuration belong in mdformat vs. those that should be implemented as plugins. I believe this philosophy is strongly held and would should be proactively communicated.

It's hard to come up with a general rule that's always correct. I think 99% of all configurability belongs in a plugin, but when not it probably needs to be reviewed. Not sure where or how to document this more clearly than the contributing docs already do. Issue templates perhaps? Those we inherit from the organization and I honestly never evaluated whether they make any sense or no.

> PRs and issues should be reviewed and/or closed accordingly because some have been in limbo for years.

Yeah, this would be ideal. It's probably better not to have much expectations for anything or anyone though. This is open source, and essentially, a hobby.

**Comment by KyleKing** [comment]
I'm glad to see so much activity again!

> I've recently thought it may be best to _reduce_ the amount of plugins we refer to in the docs to just a few essential ones like `mdformat-gfm`, and make it very clear the list is non-comprehensive. Then point to [github.com/topics/mdformat](https://github.com/topics/mdformat) for more.
> 
> I can't guarantee the quality or maintenance status of plugins other people develop so probably best not to "bless" any of them, or set false expectations of the comprehensiveness of the manually maintained plugin list.

That seems reasonable to me and would be one less source of maintenance work
 
> > There should be official documentation and/or guidance to clarify what kinds of configuration belong in mdformat vs. those that should be implemented as plugins. I believe this philosophy is strongly held and would should be proactively communicated.
> 
> It's hard to come up with a general rule that's always correct. I think 99% of all configurability belongs in a plugin, but when not it probably needs to be reviewed. Not sure where or how to document this more clearly than the contributing docs already do. Issue templates perhaps? Those we inherit from the organization and I honestly never evaluated whether they make any sense or no.
> 
> > PRs and issues should be reviewed and/or closed accordingly because some have been in limbo for years.
> 
> Yeah, this would be ideal. It's probably better not to have much expectations for anything or anyone though. This is open source, and essentially, a hobby.

No, of course not. To clarify, my goal was to help onboard new maintainers who can point to clear guidelines for consistency when you're not available (to distribute the workload where possible). I missed the paragraph in Contributing, but I think that is the right place and is sufficient. A number of the issues and PRs that I listed have already been resolved (🚀) or pending input, so I'm going to close this ticket
