### ISSUE TITLE
Proposal: `--write-to-stdout-on-ast-error`

### ISSUE THREAD

**Issue by KyleKing** [executablebooks/mdformat#467]
### Context

When debugging issues, it would be helpful if users could just write the incorrect changes anyway. This way, when someone sees the message from #463, they can post the incorrect changes to help maintainers replicate and debug the issue. Adding a workaround like this to a local fork of mdformat has been part of my workflow in the past

### Proposal

When there is an ast error detected and the CLI argument is provided, `mdformat` could write to STDOUT

```python
                if opts["write_to_stdout_on_ast_error"]:
                    sys.stdout.buffer.write(formatted_str.encode())
                print_error(
                    f'Could not format "{path_str}".',
                    ...
```

**Comment by hukkin** [comment]
Thanks for the issue! Would https://github.com/executablebooks/mdformat/issues/50 work here?

**Comment by KyleKing** [comment]
Yeah, I like either `--unsafe` or `--skip-validation`

**Comment by hukkin** [comment]
:+1: closing this in favor of https://github.com/executablebooks/mdformat/issues/50 then
