### ISSUE TITLE
Breaking (?) changes in 0.7.18 -> 0.7.19

### ISSUE THREAD

**Issue by oponomarov-tu** [executablebooks/mdformat#480]
### Describe the bug

This might not strictly be a bug, but I find this behavior disruptive. Upon updating from 0.7.18 to 0.7.19, I observed the following changes. After reviewing the [changelog](https://github.com/executablebooks/mdformat/blob/master/docs/users/changelog.md#0719), it's unclear to me whether this change was intentional or how I might revert to the previous behavior. Could you clarify?

![Screenshot 112](https://github.com/user-attachments/assets/a3a1e7a1-729f-4b1d-840b-61463b414b35)

### Reproduce the bug

N/A

### List your environment

N/A

**Comment by hukkin** [comment]
Please run `mdformat --version` as asked by the issue template.

The table syntax is not CommonMark so vanilla mdformat will wrap it. I suspect you don't have `mdformat-tables` installed, which you should if you use that syntax.

Mdformat explicitly has [no promise](https://mdformat.readthedocs.io/en/stable/users/changelog.html#changelog) of stable formatting style so style changes are not considered breaking.

**Comment by oponomarov-tu** [comment]
Hi @hukkin,

> run `mdformat --version` as asked by the issue template.

It's a bit tricky to do so when `mdformat` is used exclusively as a `pre-commit` from your repository. We're keeping dependencies up-to-date via Renovate, so given the following change:

```diff
diff --git a/.pre-commit-config.yaml b/.pre-commit-config.yaml
index d82556b..38b1918 100644
--- a/.pre-commit-config.yaml
+++ b/.pre-commit-config.yaml
@@ -34,7 +34,7 @@ repos:
           )$
 
   - repo: https://github.com/executablebooks/mdformat
-    rev: 0.7.18
+    rev: 0.7.19
     hooks:
     - id: mdformat
       additional_dependencies:
```

My best guess is that version `0.7.18` worked fine, while `0.7.19` introduced the reformat issue. 

Regardless, adding `mdformat-tables` to the `additional_dependencies` resolved the problem — thanks for the suggestion! 👍

---

That said, I don’t entirely agree that this isn’t a breaking change. While it may appear to be a style adjustment, it does result in Markdown being reformatted, which in turn causes people's "testing" pipeline to fail. For many teams, including ours, automerge is enabled for SemVer patch updates from tools like Renovate precisely because such changes should **not** result in red pipelines.

I’d kindly ask you to consider using at least a minor version bump for updates like this in the future. It would also help to make such changes more prominent in the changelog, as they can easily be overlooked.

To be clear, I deeply appreciate the work you’re doing and the value of your contributions to open source. Thank you again for your efforts!  🙌

**Comment by hukkin** [comment]
> Regardless, adding mdformat-tables to the additional_dependencies resolved the problem

Glad to hear that it worked!

> I don’t entirely agree that this isn’t a breaking change. While it may appear to be a style adjustment, it does result in Markdown being reformatted, which in turn causes people's "testing" pipeline to fail. For many teams, including ours, automerge is enabled for SemVer patch updates from tools like Renovate precisely because such changes should not result in red pipelines.

Thanks for the feedback! Maybe renovate shouldn't automerge on patch updates if [major version is zero](https://semver.org/#spec-item-4) though? I'll consider this in the future regardless (and try to reach v1.0.0).
