### ISSUE TITLE
Host documentation on readthedocs.io

### ISSUE THREAD

**Issue by hukkinj1** [executablebooks/mdformat#72]
- [ ] Create docs with either
      - MkDocs
      - Sphinx + CommonMark or MyST

- [ ]  Build the docs in Github Actions.

- [ ]  Publish on readthedocs.io

**Comment by chrisjsewell** [comment]
Ideally Sphinx + MyST + RTD, the same as the rest of EBP 😬

You don't actually need to run a GH action, just turn on PR runs on RTD:
https://docs.readthedocs.io/en/stable/guides/autobuild-docs-for-pull-requests.html

**Comment by hukkinj1** [comment]
Thanks for the input, I really don't have much experience in any of this.

Sphinx + MyST + RTD sounds great. Or if we want to keep using `pre-commit try-repo ...` to run mdformat against its own docs, then maybe start with Sphinx + CommonMark and move to MyST, when we can come up with the necessary plugins for mdformat to handle MyST? I kinda like the `pre-commit try-repo` in that it shows we trust the tool enough to format our own docs with it, and also makes mdformat docs showcase what the output looks like.

> You don't actually need to run a GH action, just turn on PR runs on RTD:

Nice! Maybe it's possible to use a GH action to "validate" the docs though? Fail CI if docs fail building, so we know not to merge a PR unless the docs are fixed? Or does Sphinx build ever fail? I'm still a noob here :smile:

**Comment by chrisjsewell** [comment]
> Sphinx + CommonMark and move to MyST

Oh MyST is already commonmark compliant. Its just add extra (optional) syntax plugins to the parser. If you don't use them, then it works exactly the same as CommonMark (we are in fact in talks with RTD to deprectate ReCommonMark in favour of MyST)

> Fail CI if docs fail building

Yep this already happens with the RTD builds (you can see the check e.g. in https://github.com/executablebooks/markdown-it-py/pull/58), you just need to add to the repo https://github.com/executablebooks/markdown-it-py/blob/master/.readthedocs.yml

**Comment by chrisjsewell** [comment]
I can try to get round to making a PR for it at som point 😄

**Comment by hukkinj1** [comment]
> Its just add extra (optional) syntax plugins to the parser.

Yeah this is what I was thinking could be problematic. But I think you are right, we don't really have to use the extra syntax and if we want to in some files, then skip mdformatting that file etc.

> Yep this already happens with the RTD builds

Nice!

> I can try to get round to making a PR for it at some point smile

This would be amazing!
