### ISSUE TITLE
GFM support

### ISSUE THREAD

**Issue by hukkinj1** [executablebooks/mdformat#82]
Come up with the necessary plugins to format Github Flavored Markdown.

### Features

- [x] Tables ([mdformat-tables](https://github.com/executablebooks/mdformat-tables))
- [x] Task list items ([mdformat-gfm](https://github.com/hukkinj1/mdformat-gfm))
- [x] Strikethrough ([mdformat-gfm](https://github.com/hukkinj1/mdformat-gfm))
- [x] Extended autolinks (not sure if changes needed, not making any right now)
- [x] Disallowed raw HTML (no changes needed)

### Collection plugin
It might make sense to make a collection plugin (e.g. `mdformat-gfm`) that installs all GFM extensions.

### Resources
- Task list plugin about to be merged to markdown-it-py: https://github.com/executablebooks/markdown-it-py/pull/76
- Strikethrough extension already a part of markdown-it-py: https://github.com/executablebooks/markdown-it-py/blob/master/markdown_it/rules_inline/strikethrough.py

**Comment by hukkinj1** [comment]
Work started here https://github.com/hukkinj1/mdformat-gfm

**Comment by wna-se** [comment]
Would [GitHub flavoured emoji](https://www.webfx.com/tools/emoji-cheat-sheet/) be out of scope for this? E.g. 
[markdown-it-emoji](https://github.com/markdown-it/markdown-it-emoji).

**Comment by hukkinj1** [comment]
I'd say that's out of scope, as I'm going strictly for what's in https://github.github.com/gfm/ here. Also I think the emoji conversion should be a feature of a Markdown to HTML renderer, so I think a formatter that only deals with Markdown shouldn't care about this.

**Comment by hukkinj1** [comment]
Done. For GFM support, do
```sh
pip install mdformat-gfm
```
