### ISSUE TITLE
Convert list item markers

### ISSUE THREAD

**Issue by hukkinj1** [executablebooks/mdformat#83]
Convert list item marker symbols. For unordered lists, always prefer `-`. If there are sequential lists, alternate between `-` and `*`.

Do the same for ordered lists using `.` (preferred) and `)`.

**Comment by unparalleled-js** [comment]
What is the reasoning for preferring `-` over `*` ?
What it make sense to allow this to be configurable?

**Comment by hukkin** [comment]
There is no reason besides that mdformat is opinionated and happens to prefer `-`. See https://mdformat.readthedocs.io/en/stable/contributors/contributing.html#contributing on adding configuration options.

**Comment by unparalleled-js** [comment]
Based on this sentence from the contributing guide:

> Note that mdformat is an opinionated tool that attempts to keep formatting style changing configuration to its minimum. ? > New configuration will only be added for a very good reason and use case.

I sense that a PR that adds a configuration option for preferring `*` may not be wanted.

I do personally prefer the `*` a little more because I can't see the hyphen symbol very well, but it is NBD.

**Comment by hukkin** [comment]
Yes, I don't think this is a strong enough reason to justify the conf option.
